
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 27 22:23:18 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Estatico = 24;
  public static final int Llave_c = 15;
  public static final int Llave_a = 14;
  public static final int If = 4;
  public static final int Comparacion = 31;
  public static final int Clase = 22;
  public static final int Menor = 27;
  public static final int Else = 5;
  public static final int D_String = 34;
  public static final int Mayor = 28;
  public static final int Punto = 36;
  public static final int Vacio = 25;
  public static final int N_Clase = 23;
  public static final int While = 6;
  public static final int Division = 11;
  public static final int Int = 3;
  public static final int Cadena = 33;
  public static final int Parentesis_c = 13;
  public static final int Publico = 21;
  public static final int Parentesis_a = 12;
  public static final int Logicos = 26;
  public static final int EOF = 0;
  public static final int P_coma = 17;
  public static final int error = 1;
  public static final int Distinto = 32;
  public static final int Imprimir = 35;
  public static final int ERROR = 19;
  public static final int MenorIgual = 29;
  public static final int Paquete = 2;
  public static final int Identificador = 18;
  public static final int Resta = 9;
  public static final int MayorIgual = 30;
  public static final int Multiplicacion = 10;
  public static final int Importar = 20;
  public static final int Numero = 37;
  public static final int Suma = 8;
  public static final int Main = 16;
  public static final int Igual = 7;
}

